now we check the ngx_devel_kit dependency at config time and provide a more friendly error message if it is missing.

diff --git a/config b/config
--- a/config
+++ b/config
@@ -1,3 +1,10 @@
+if echo $HTTP_MODULES | grep " ndk_http_module" > /dev/null; then
+    echo "found ngx_devel_kit for ngx_iconv; looks good."
+else
+    echo "error: ngx_devel_kit is required to build ngx_iconv; please put it before ngx_iconv." 1>&2
+    exit 1
+fi
+
 ngx_feature_name=
 ngx_feature_run=no
 ngx_feature_incs="#include <iconv.h>"
